# Generated by Django 5.1.7 on 2025-03-12 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='blog/images')),
                ('updated_at', models.DateTimeField(verbose_name=datetime.date.today)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
